# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

references:
  working_directory: &working_directory
    ~/bedrock

  # Default container configuration
  #
  container_config: &container_config
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3 #-node-browsers
    working_directory: *working_directory

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *working_directory

jobs:
  build:
    <<: *container_config

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: composer install -n -o
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  test:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Run tests
          command: composer test

  deploy:
    <<: *container_config
    steps:
      - *attach_workspace
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "97:c9:de:a6:00:9b:12:88:43:d0:d3:af:fc:fc:c1:ac"
      - run:
          name: Install rsync
          command: >-
            sudo apt-get update &&
            sudo apt-get install rsync
      - run:
          name: Update environment variables
          command: |
            echo 'if [ "$CIRCLE_BRANCH" == "production" ]; then export SSH_PORT="$PRODUCTION_SSH_PORT"; else export SSH_PORT="$STAGING_SSH_PORT"; fi;' >> $BASH_ENV
            echo 'if [ "$CIRCLE_BRANCH" == "production" ]; then export WP_HOME="$PRODUCTION_WP_HOME"; else export WP_HOME="$STAGING_WP_HOME"; fi;' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install deploy script
            # command uses folded block scalar syntax
          command: >-
            ssh-keygen -F $SSH_HOST >/dev/null || ssh-keyscan -p $SSH_PORT -H $SSH_HOST >> ~/.ssh/known_hosts &&
            ssh $SSH_USER@$SSH_HOST -p $SSH_PORT "mkdir -p public/tmp" &&
            rsync -avz -e "ssh -p $SSH_PORT" scripts/deploy.sh $SSH_USER@$SSH_HOST:public/tmp/deploy.sh &&
            ssh $SSH_USER@$SSH_HOST -p $SSH_PORT bash 'public/tmp/deploy.sh' $CIRCLE_BRANCH $WP_HOME

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - production
                - main
