<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'NF_FU_VENDOR\\phpseclib\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'NF_FU_VENDOR\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'NF_FU_VENDOR\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'NF_FU_VENDOR\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'NF_FU_VENDOR\\Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'NF_FU_VENDOR\\Polevaultweb\\WPOAuth2\\' => array($vendorDir . '/polevaultweb/wp-oauth2/src'),
    'NF_FU_VENDOR\\Polevaultweb\\WPDropboxAPI\\' => array($vendorDir . '/polevaultweb/wp-dropbox-api/src'),
    'NF_FU_VENDOR\\Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'NF_FU_VENDOR\\JmesPath\\' => array($vendorDir . '/mtdowling/jmespath.php/src'),
    'NF_FU_VENDOR\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'NF_FU_VENDOR\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'NF_FU_VENDOR\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'NF_FU_VENDOR\\Google\\Auth\\' => array($vendorDir . '/google/auth/src'),
    'NF_FU_VENDOR\\Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'NF_FU_VENDOR\\Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'NF_FU_VENDOR\\Aws\\' => array($vendorDir . '/aws/aws-sdk-php/src'),
);
