# This workflow deploys the Frocentric WordPress application on a successful push or PR

name: PR Auto Merge

# Controls when the action will run. Triggers the workflow on pull request events
on:
  pull_request:
    branches: [ main, production ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          target: patch
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
