# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Backs up repo
    #- name: Backup Repo
    #  run: git clone --mirror git@github.com:frocentric/wordpress.git
        
    # Syncs the repository with Fortrabbit
    - name: Sync Repo
      uses: wei/git-sync@v2.0.0
      with:
        # GitHub repo slug or full clone url
        source_repo: "frocentric/wordpress"
        # Branch name to sync from
        source_branch: "main"
        # GitHub repo slug or full clone url
        destination_repo: "frowarecom@35.246.15.218:18528/www/frowarecom_769/private/frowarecom.git"
        # Branch name to sync to
        destination_branch: "main"
        # SSH key used to authenticate with git clone urls provided (optional if public or https clone url with authentication)
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
